package pojo;
// Generated Oct 15, 2022 11:20:55 PM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import DAO.DAOAdmin;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;



@ManagedBean(name="TblAdmin")@ViewScoped

/**
 * TblAdmin generated by hbm2java
 */
public class TblAdmin  implements java.io.Serializable {


     private Integer adminId;
     private String adminEmail;
     private String adminName;
     private String adminPassword;
    
      public String login_admin(){
      DAOLogin uDAO= new DAOLogin();
      List<TblAdmin> ad = uDAO.getByAdmin(adminName, adminPassword);
      try {
          if (ad !=null){
              adminName=ad.get(0).adminName;
              adminPassword=ad.get(0).adminPassword;
              return "admin_page.xhtml";
          }
      } catch (Exception e){
          System.out.println(e);
          
      }
     return "login_gagal.xhtml";     
  } 
     
    public TblAdmin() {
    }

    public TblAdmin(String adminEmail, String adminName, String adminPassword) {
       this.adminEmail = adminEmail;
       this.adminName = adminName;
       this.adminPassword = adminPassword;
    }
   
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
    public String getAdminEmail() {
        return this.adminEmail;
    }
    
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }
    public String getAdminPassword() {
        return this.adminPassword;
    }
    
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }

    public Object getAdmin_id() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Object getUsername() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Object getPassword() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


